module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "colors-dark-100": "var(--colors-dark-100)",
        "colors-dark-1000": "var(--colors-dark-1000)",
        "colors-dark-250": "var(--colors-dark-250)",
        "colors-dark-50": "var(--colors-dark-50)",
        "colors-dark-500": "var(--colors-dark-500)",
        "colors-dark-750": "var(--colors-dark-750)",
        "colors-light-100": "var(--colors-light-100)",
        "colors-light-1000": "var(--colors-light-1000)",
        "colors-light-250": "var(--colors-light-250)",
        "colors-light-50": "var(--colors-light-50)",
        "colors-light-500": "var(--colors-light-500)",
        "colors-light-750": "var(--colors-light-750)",
        "colors-primary-100": "var(--colors-primary-100)",
        "colors-primary-1000": "var(--colors-primary-1000)",
        "colors-primary-500": "var(--colors-primary-500)",
        colorsblack: "var(--colorsblack)",
      },
      fontFamily: {
        "body-bold-lg": "var(--body-bold-lg-font-family)",
        "body-bold-md": "var(--body-bold-md-font-family)",
        "body-bold-sm": "var(--body-bold-sm-font-family)",
        "body-bold-xl": "var(--body-bold-xl-font-family)",
        "body-bold-xs": "var(--body-bold-xs-font-family)",
        "body-bold-xxl": "var(--body-bold-xxl-font-family)",
        "body-regular-lg": "var(--body-regular-lg-font-family)",
        "body-regular-md": "var(--body-regular-md-font-family)",
        "body-regular-sm": "var(--body-regular-sm-font-family)",
        "body-regular-xl": "var(--body-regular-xl-font-family)",
        "body-regular-xs": "var(--body-regular-xs-font-family)",
        "body-regular-xxl": "var(--body-regular-xxl-font-family)",
        "heading-h1": "var(--heading-h1-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h4": "var(--heading-h4-font-family)",
        "heading-h5": "var(--heading-h5-font-family)",
        "heading-h6": "var(--heading-h6-font-family)",
        "heading-h7": "var(--heading-h7-font-family)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
